#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const manifest = require("../public/manifest.json");

manifest.version = process.argv.slice[2];

fs.writeFileSync(
  path.join(__dirname, "..", "public", "manifest.json"),
  JSON.stringify(manifest, null, 2) + "\n"
);
